//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.BooksRead.Web.Models
{
    using Repository;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    [Table("Product")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductNotifications = new HashSet<ProductNotification>();
            this.ProductSubscriptions = new HashSet<ProductSubscription>();
        }
        public static Product Instance()
        {
            return new Product();
        }
        public Product CreateProduct(int? productId)
        {
            //ProductRepo = Resolver.Container.Resolve<IProductRepository>();
            return ProductRepo.GetProductById(productId);
        }

        public IProductRepository ProductRepo
        {
            get
            {
                if (productrepo != null)
                {
                    return productrepo;
                }
                return DependencyResolver.Current.GetService<IProductRepository>();

            }
            set { productrepo = value; }
        }

        private IProductRepository productrepo;
        public int Id { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Category Category1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductNotification> ProductNotifications { get; set; }

        public void Update(ProductViewModel priceChangeProduct)
        {
           
            if (this.Price != priceChangeProduct.Price)
            {
                this.PriceIsChanged = true;
                var productNotification = new ProductNotification();
                productNotification.Notification =
                    string.Format(Common.Utility.PRODUCT_PRICE_CHANGE_NOTIFICATION,
                    new object[] {
                        this.Id.ToString(),
                        this.Name,
                        this.Price.ToString(),
                        priceChangeProduct.Price.ToString() });

                this.ProductNotifications.Add(productNotification);
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSubscription> ProductSubscriptions { get; set; }
        public INotificationRepository NotificationRepo { get; set; }
        public bool PriceIsChanged { get; private set; }
    }
}
