//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.BooksRead.Web
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
