//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.BooksRead.Web.DTO
{
    using Repository;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    
    public class ProductDto
    {
       
        public ProductDto()
        {}
        
        public int Id { get; set; }
        public string Name { get; set; }
    
      
    }
}
